backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collection:
  - name: "photo"
    label: "Photo"
    folder: "content/photos/"
    create: true
    slug: "{{title}}-{{day}}-{{month}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "photo" }
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Catégorie", name: "category", widget: "relation" }
      - { label: "Description", name: "description", widget: "string" }
