backend:
  name: git-gateway
  repo: Halias3422/evaluation_front-end
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

locale: "fr"

collections:
  - name: "photos"
    label: "Photos"
    folder: "content/photos/"
    create: true
    slug: "{{title}}-{{year}}-{{month}}-{{day}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "photos"
      - label: "Titre"
        name: "title"
        widget: "string"
      - label: "Date de publication"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        time_format: true
        format: "DD.MM.YYYY"
      - label: "Image petit format"
        name: "imageSmall"
        widget: "object"
        fields:
          - label: "image"
            name: "image"
            widget: "image"
          - label: "largeur"
            name: "width"
            widget: "number"
          - label: "hauteur"
            name: "height"
            widget: "number"
      - label: "Image grand format"
        name: "imageBig"
        widget: "object"
        fields:
          - label: "image"
            name: "image"
            widget: "image"
          - label: "largeur"
            name: "width"
            widget: "number"
          - label: "hauteur"
            name: "height"
            widget: "number"
      - label: "Catégorie"
        name: "category"
        widget: "relation"
        collection: "categories"
        value_field: "name"
        search_fields: ["name"]
        multiple: true
        min: 1
        max: 1

  - name: "categories"
    label: "Catégories"
    folder: "content/categories/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "categories"
      - label: "Nom"
        name: "name"
        widget: "string"
